feat(tg_dry_001): init
padok-team/guacamole pull request #63
Opened 2024-01-09 16:52 UTC by Laudenlaruto

- Split static checks between those for modules and those for layers
- Implement the 1st layer check : Input should be unique

2024-01-26 15:03 UTC, cterence requested changes

2024-01-26 15:03 UTC, cterence commented on cmd/static_check_layer.go
> +}
It should state that it should be run from within the directory of the codebase because if we run it elsewhere, it breaks many terragrunt functions

![Screenshot from 2024-01-26 15-59-21](https://github.com/padok-team/guacamole/assets/25285508/11f3ac5c-26a0-4d6b-9f7a-073b83402330)

2024-01-29 10:31 UTC, Laudenlaruto commented on cmd/static_check_layer.go
> +}
It was an issue with the function get_original_terragrunt_dir. Fixed in the latest commit.

2024-01-29 13:07 UTC, cterence commented on cmd/static_check_layer.go
> +}
OK it worked !

2024-01-29 16:22 UTC, merged